{
 "title": "MongoDB FTDC Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Assessment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stats & Scores",
   "type": "table-old",
   "description": "Each metrics is scored by its utilization.",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "targets": [
    { "target": "assessment", "type": "table" }
   ]
  },
  {
   "title": "Host Info",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "targets": [
    { "target": "host_info", "type": "table" }
   ]
  },
  {
   "title": "WiredTiger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WiredTiger Tickets",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "ticket_avail_read", "type": "timeserie" },
      { "target": "ticket_avail_write", "type": "timeserie" }
     ]
    },
    {
     "title": "WiredTiger Cache",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      { "target": "wt_cache_max", "type": "timeserie" },
      { "target": "wt_cache_used", "type": "timeserie" },
      { "target": "wt_cache_dirty", "type": "timeserie" }
     ]
    },
    {
     "title": "WiredTiger Cache Pages Evicted",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "wt_modified_evicted", "type": "timeserie" },
      { "target": "wt_unmodified_evicted", "type": "timeserie" }
     ]
    },
    {
     "title": "WiredTiger Cache I/O",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "target": "wt_cache_read_in", "type": "timeserie" },
      { "target": "wt_cache_written_from", "type": "timeserie" }
     ]
    },
    {
     "title": "WiredTiger Block Manager",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "target": "wt_blkmgr_read", "type": "timeserie" },
      { "target": "wt_blkmgr_written", "type": "timeserie" },
      { "target": "wt_blkmgr_written_checkpoint", "type": "timeserie" }
     ]
    },
    {
     "title": "WiredTiger Data Handle",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "wt_dhandles_active", "type": "timeserie" }
     ]
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      { "target": "mem_virtual", "type": "timeserie" },
      { "target": "mem_resident", "type": "timeserie" }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "target": "latency_read", "type": "timeserie" },
      { "target": "latency_write", "type": "timeserie" },
      { "target": "latency_command", "type": "timeserie" }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "conns_current", "type": "timeserie" },
      { "target": "conns_created/s", "type": "timeserie" },
      { "target": "conns_active", "type": "timeserie" }
     ]
    },
    {
     "title": "Network Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "net_requests", "type": "timeserie" }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "mem_page_faults", "type": "timeserie" }
     ]
    },
    {
     "title": "Ops Counters",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "ops_query", "type": "timeserie" },
      { "target": "ops_insert", "type": "timeserie" },
      { "target": "ops_update", "type": "timeserie" },
      { "target": "ops_delete", "type": "timeserie" },
      { "target": "ops_getmore", "type": "timeserie" },
      { "target": "ops_command", "type": "timeserie" }
     ]
    },
    {
     "title": "Queued Ops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "q_queued_read", "type": "timeserie" },
      { "target": "q_queued_write", "type": "timeserie" }
     ]
    },
    {
     "title": "Network Bytes In/Out",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "target": "net_in", "type": "timeserie" },
      { "target": "net_out", "type": "timeserie" }
     ]
    },
    {
     "title": "Replication Lags",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "target": "replication_lags", "type": "timeserie" }
     ]
    },
    {
     "title": "Query Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "scan_objects", "type": "timeserie" },
      { "target": "scan_keys", "type": "timeserie" },
      { "target": "scan_sort", "type": "timeserie" }
     ]
    },
    {
     "title": "Ops In Progress",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "q_active_read", "type": "timeserie" },
      { "target": "q_active_write", "type": "timeserie" }
     ]
    },
    {
     "title": "Network Physical Bytes In/Out",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "target": "net_physical_in", "type": "timeserie" },
      { "target": "net_physical_out", "type": "timeserie" }
     ]
    }
   ]
  },
  {
   "title": "TCMalloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Generic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "tcmalloc_current_allocated_bytes",
       "type": "timeserie"
      },
      { "target": "tcmalloc_heap_size", "type": "timeserie" },
      { "target": "tcmalloc_total_free_bytes", "type": "timeserie" }
     ]
    },
    {
     "title": "Spinlock Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "target": "tcmalloc_spinlock_total_delay_ns",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Caches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "tcmalloc_central_cache_free_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_current_total_thread_cache_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_transfer_cache_free_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_thread_cache_free_bytes",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "PageHeap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "target": "tcmalloc_pageheap_free_bytes", "type": "timeserie" },
      {
       "target": "tcmalloc_pageheap_unmapped_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_pageheap_committed_bytes",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "PageHeap Commit/Decommit/Reserve Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "tcmalloc_pageheap_total_commit_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_pageheap_total_decommit_bytes",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_pageheap_total_reserve_bytes",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "PageHeap Commit/Decommit/Reserve/Scavenge Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "target": "tcmalloc_pageheap_commit_count", "type": "timeserie" },
      {
       "target": "tcmalloc_pageheap_decommit_count",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_pageheap_reserve_count",
       "type": "timeserie"
      },
      {
       "target": "tcmalloc_pageheap_scavenge_count",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics (CPU & Disks)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "target": "cpu_system", "type": "timeserie" },
      { "target": "cpu_user", "type": "timeserie" },
      { "target": "cpu_iowait", "type": "timeserie" },
      { "target": "cpu_nice", "type": "timeserie" }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "disks_iops", "type": "timeserie" }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "target": "disks_utils", "type": "timeserie" }
     ]
    },
    {
     "title": "I/O In Progress",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "disks_queue_length", "type": "timeserie" }
     ]
    },
    {
     "title": "Disk Total Wait Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "target": "io_queued_ms", "type": "timeserie" }
     ]
    },
    {
     "title": "Disk Read Wait Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "target": "read_time_ms", "type": "timeserie" }
     ]
    },
    {
     "title": "Disk Write Wait Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "target": "write_time_ms", "type": "timeserie" }
     ]
    }
   ]
  }
 ]
}