{
 "title": "Keyhole Analytics",
 "time": { "from": "2017-10-12T17:55:08.214Z", "to": "2017-10-27T21:46:57.613Z" },
 "panels": [
  {
   "title": "WiredTiger Cache (GB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "wt_cache_max", "type": "timeserie" },
    { "target": "wt_cache_used", "type": "timeserie" },
    { "target": "wt_cache_dirty", "type": "timeserie" }
   ]
  },
  {
   "title": "Latencies (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "latency_read", "type": "timeserie" },
    { "target": "latency_write", "type": "timeserie" },
    { "target": "latency_command", "type": "timeserie" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "conns_current", "type": "timeserie" },
    { "target": "conns_created_per_minute", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cpu_system", "type": "timeserie" },
    { "target": "cpu_user", "type": "timeserie" },
    { "target": "cpu_iowait", "type": "timeserie" },
    { "target": "cpu_idle", "type": "timeserie" },
    { "target": "cpu_nice", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Paging (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "wt_modified_evicted", "type": "timeserie" },
    { "target": "wt_unmodified_evicted", "type": "timeserie" },
    { "target": "wt_read_in_cache", "type": "timeserie" },
    { "target": "wt_written_from_cache", "type": "timeserie" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "q_active_read", "type": "timeserie" },
    { "target": "q_active_write", "type": "timeserie" },
    { "target": "q_queued_read", "type": "timeserie" },
    { "target": "q_queued_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Ops Counters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ops_query", "type": "timeserie" },
    { "target": "ops_insert", "type": "timeserie" },
    { "target": "ops_update", "type": "timeserie" },
    { "target": "ops_delete", "type": "timeserie" },
    { "target": "ops_getmore", "type": "timeserie" },
    { "target": "ops_command", "type": "timeserie" }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "mem_virtual", "type": "timeserie" },
    { "target": "mem_resident", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Tickets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ticket_avail_read", "type": "timeserie" },
    { "target": "ticket_avail_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "scan_objects", "type": "timeserie" },
    { "target": "scan_keys", "type": "timeserie" },
    { "target": "scan_sort", "type": "timeserie" }
   ]
  },
  {
   "title": "Replication Lags (seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "replication_lags", "type": "timeserie" }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "mem_page_faults", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disks_utils", "type": "timeserie" }
   ]
  }
 ]
}