name: Lint

on:
  - push
  - pull_request

env:
  CGO_LDFLAGS_ALLOW: "-s|-w"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache mods
        uses: actions/cache@v3
        with:
          path:  |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Download mods
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout 2m0s
          skip-cache: true
