name: Test

on:
  - push
  - pull_request

env:
  CGO_LDFLAGS_ALLOW: "-s|-w"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18.x", "1.17.x", "1.16.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache mods
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Download mods
        run: go mod download
      - name: Test
        run: go test ./...

